/*
 * This file was generated by the mkbuiltins program.
 */

#define BLTINCMD 0
#define COMMANDCMD 1
#define BREAKCMD 2
#define CDCMD 3
#define DOTCMD 4
#define ECHOCMD 5
#define EVALCMD 6
#define EXECCMD 7
#define EXITCMD 8
#define EXPCMD 9
#define EXPORTCMD 10
#define EXPRCMD 11
#define FALSECMD 12
#define HISTCMD 13
#define GETOPTSCMD 14
#define HASHCMD 15
#define JOBIDCMD 16
#define JOBSCMD 17
#define LOCALCMD 18
#define PWDCMD 19
#define READCMD 20
#define RETURNCMD 21
#define SETCMD 22
#define SETVARCMD 23
#define SHIFTCMD 24
#define TRAPCMD 25
#define TRUECMD 26
#define TYPECMD 27
#define UMASKCMD 28
#define UNALIASCMD 29
#define UNSETCMD 30
#define WAITCMD 31
#define ALIASCMD 32
#define ULIMITCMD 33
#define BINDCMD 34
#define WORDEXPCMD 35

struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[]) (int, char **);
extern const struct builtincmd builtincmd[];
int bltincmd (int, char **);
int commandcmd (int, char **);
int breakcmd (int, char **);
int cdcmd (int, char **);
int dotcmd (int, char **);
int echocmd (int, char **);
int evalcmd (int, char **);
int execcmd (int, char **);
int exitcmd (int, char **);
int expcmd (int, char **);
int exportcmd (int, char **);
int exprcmd (int, char **);
int falsecmd (int, char **);
int histcmd (int, char **);
int getoptscmd (int, char **);
int hashcmd (int, char **);
int jobidcmd (int, char **);
int jobscmd (int, char **);
int localcmd (int, char **);
int pwdcmd (int, char **);
int readcmd (int, char **);
int returncmd (int, char **);
int setcmd (int, char **);
int setvarcmd (int, char **);
int shiftcmd (int, char **);
int trapcmd (int, char **);
int truecmd (int, char **);
int typecmd (int, char **);
int umaskcmd (int, char **);
int unaliascmd (int, char **);
int unsetcmd (int, char **);
int waitcmd (int, char **);
int aliascmd (int, char **);
int ulimitcmd (int, char **);
int bindcmd (int, char **);
int wordexpcmd (int, char **);
