/*
 * This file was generated by the mksignames program.
 */

#include "shell.h"

char *const sigmesg[26] = {
      0,
      "Hangup",
      "Interrupt",
      "Quit",
      "Illegal instruction",
      "Trace/BPT trap",
      "abort",
      "Bus error",
      "Floating exception",
      "Killed",
      "User signal 1",
      "Memory fault",
      "User signal 2",
      "Broken pipe",
      "Alarm call",
      "Terminated",
      "EMT trap",
      0,
      0,
      "Stopped",
      "Stopped",
      0,
      "Stopped (input)",
      "Stopped (output)",
      "Virtual alarm",
      "Profiling alarm",
};
